### ISSUE TITLE
Create standalone s3fs package

### ISSUE THREAD

**Issue by fmarczin** [adamlwgriffiths/pyfilesystem#1]
Hi,

I would like to add support for arbitrary S3 services (along the lines of https://code.google.com/p/pyfilesystem/issues/detail?id=190#c6) and possibly also contribute further to the "sanity" of this backend. But since your changes and mine as well only concern S3, it seems more appropriate to maintain this as a filesystem implementation and not as a fork of PyFilesystem.

What do you think?

Cheers, Felix

**Comment by adamlwgriffiths** [comment]
I havent fully tested this code and have been tempted to delete the repository.
I think PyFS is a good idea, but it will snap people in the butt when they realise the $ it will impose for S3.
File systems and KV stores are two different things.
Thats why my friend and I created KVStore =P
https://github.com/chrsbats/kvstore

It can switch between S3 and local FS.
We haven't gotten around to putting it on PyPi yet.
Hopefully we'll do that soon.

For all intents and purposes, this project is dead and is just sitting in my heap of projects.

Thanks for your awesome offer of collaboration, always appreciated XD
Take a look at Kvstore, see if it fits your needs and let me know what you think.

Edit:
I've added a note to the README regarding this project's status and kvstore.

**Comment by fmarczin** [comment]
kvstore looks cool, I especially like how little code it actually is! Makes PyFS-S3 look even more messy in comparison. After checking PyPI and googling around, I was under the impression that there are no other projects that provide a single API for local file systems and S3, not to mention other FS. I will show kvstore to my colleagues together with PyFS.

I actually have a need for putting a local FS, S3, SFTP and other things behind the same API. I totally agree that using FS semantics against a KV store is prone to lead to disappointment, though. 

Since in my case, we host our own S3 storage, the issues with PyFS are much less pressing, and I _really_ like stuff like MultiFS, MemoryFS, etc. Do you think those would make sense to add to kvstore, or would you rather keep a more narrow scope?

**Comment by adamlwgriffiths** [comment]
The core idea is that 'get' and 'put' is really the basic use case for data storage.

PyFilesystem guarantees to act like a proper file system, it puts special markers on s3 for 'directories' and others for files. It also lets you create directories separately from files. Etc. Etc.
Hence it's expensive because a delete operation goes and checks for these markers before actually deleting. So 1 operation becomes 2, becomes 3, becomes 5.

Kvstore can be used for filesystems because we just create directories when we write files.
So technically it should be easier to support more backends than PyFilesystem can.

Not to bash on PyFilesystem. It's a great lib, but it's targeted at FS level which really doesn't work with KV.

Anyway. Additional backends are welcome. Feel free to discuss further or go ahead and submit pull requests =)

**Comment by fmarczin** [comment]
Ok, cool. I guess we need to pick KV vs. FS semantics first, and then decide on an implementation. Let's see where that leads us.
